# Generated by Django 2.2.1 on 2019-12-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembling',
            fields=[
                ('assembling_id', models.AutoField(primary_key=True, serialize=False)),
                ('assembling_code', models.CharField(max_length=45)),
                ('assembling_line', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['assembling_code', 'assembling_line'],
                'unique_together': {('assembling_code', 'assembling_line')},
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('coordinator_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('nickname', models.CharField(blank=True, default='', max_length=45)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'nickname'],
                'unique_together': {('last_name', 'first_name', 'nickname')},
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=20)),
                ('part_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['part_number', 'part_name'],
                'unique_together': {('part_number', 'part_name')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=10)),
                ('assembling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='companyinfo2.Assembling')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='companyinfo2.Part')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='companyinfo2.Supplier')),
            ],
            options={
                'ordering': ['part__part_number', 'product_name', 'supplier__supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='Product_coordinator',
            fields=[
                ('product_coordinator_id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_coordinators', to='companyinfo2.Coordinator')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_coordinators', to='companyinfo2.Product')),
            ],
            options={
                'ordering': ['product', 'coordinator'],
                'unique_together': {('product', 'coordinator')},
            },
        ),
    ]
