# Generated by Django 2.2.1 on 2019-12-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo2', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('supplier', 'part', 'product_name')},
        ),
    ]
