# Generated by Django 2.2.1 on 2019-12-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo2', '0004_address_country_state_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=45),
        ),
    ]
