# Generated by Django 2.2.1 on 2019-12-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembling',
            options={'ordering': ['assembling_id', 'assembling_code', 'assembling_line']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='assembling',
        ),
        migrations.AddField(
            model_name='product',
            name='assembling',
            field=models.ManyToManyField(related_name='assembling', to='companyinfo.Assembling'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='part',
        ),
        migrations.AddField(
            model_name='product',
            name='part',
            field=models.ManyToManyField(related_name='part', to='companyinfo.Part'),
        ),
        migrations.AlterUniqueTogether(
            name='assembling',
            unique_together={('assembling_id', 'assembling_code', 'assembling_line')},
        ),
    ]
