# Generated by Django 3.0 on 2019-12-16 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0002_auto_20191210_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembling',
            options={'ordering': ['assembling_code', 'assembling_line']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='assembling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='part',
        ),
        migrations.AddField(
            model_name='product',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='companyinfo.Part'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='companyinfo.Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='assembling',
            unique_together=set(),
        ),
    ]
